services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    container_name: reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3005:3005'
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    container_name: auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3010:3010'
    volumes:
      - .:/usr/src/app

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    container_name: payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    container_name: notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres