apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: asia-southeast1-docker.pkg.dev/paymentapp-422116/payments/production
        name: production
        env:
          - name: MONGODB_URI
            valueFrom: 
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: PORT
            value: '3030'
          - name: NOTIFICATIONS_HOST
            value: notifications
          - name: NOTIFICATIONS_PORT
            value: '3040'
          - name: STRIPE_SECRET_KEY
            valueFrom: 
              secretKeyRef:
                name: stripe
                key: apiKey
        ports:
          - containerPort: 3030
